export const colors: string[] = ["#ff0000",
                      "#ff8000",
                      "#ffff00",
                      "#beff00",
                      "#00ff00",
                      "#00ffff",
                      "#0080ff",
                      "#0000ff",
                      "#7f00ff",
                      "#ff00ff",
                      "#ff007f",
                      "#808080",
                      "#ffffff",
                      "#000000"];